Config = {
    Component = {

    },
    ChatColors = {
        ['founder'] = {
            label = 'Founder',
            color = '#ff0000'
        },
        ['co-founder'] = {
            label = 'CO-Founder',
            color = '#ff0000'
        },
        ['developer'] = {
            label = 'Development',
            color = '#00edff'
        },
        ['superadmin'] = {
            label = 'Super-Administrator',
            color = '#ab00ff'
        },
        ['admin'] = {
            label = 'Administrator',
            color = '#f1c40f'
        },
        ['mod'] = {
            label = 'Moderator',
            color = '#0033ff'
        },
        ['supporter'] = {
            label = 'Supporter',
            color = '#28ff00'
        },
        ['user'] = {
            label = 'User',
            color = '#fff'
        },
    },
    Perms = {
        ['ban'] = {
            ['founder'] = true,
            ['admin'] = true,
        },
        ['all'] = {
            ['founder'] = true,
        },
        ['weapon'] = {
            ['founder'] = true,
        },
        ['vehicle'] = {
            ['founder'] = true
        }
    },
    StartWeapons = {
        ['WEAPON_PISTOL'] = {
            components = {}
        },
        ['WEAPON_SPECIALCARBINE_MK2'] = {
            components = {
                {
                    name = 'suppressor',
                    hash = GetHashKey('COMPONENT_AT_AR_SUPP_02')
                }
            }
        },
    },
    Components = {
        -- Melee's
        ['WEAPON_KNUCKLE'] = {
            ['base'] = GetHashKey('COMPONENT_KNUCKLE_VARMOD_BASE'),
            ['pimp'] = GetHashKey('COMPONENT_KNUCKLE_VARMOD_PIMP'),
            ['ballas'] = GetHashKey('COMPONENT_KNUCKLE_VARMOD_BALLAS'),
            ['hustler'] = GetHashKey('COMPONENT_KNUCKLE_VARMOD_DOLLAR'),
            ['rock'] = GetHashKey('COMPONENT_KNUCKLE_VARMOD_DIAMOND'),
            ['hater'] = GetHashKey('COMPONENT_KNUCKLE_VARMOD_HATE'),
            ['lover'] = GetHashKey('COMPONENT_KNUCKLE_VARMOD_LOVE'),
            ['player'] = GetHashKey('COMPONENT_KNUCKLE_VARMOD_PLAYER'),
            ['king'] = GetHashKey('COMPONENT_KNUCKLE_VARMOD_KING'),
            ['vagos'] = GetHashKey('COMPONENT_KNUCKLE_VARMOD_VAGOS')
        },
        ['WEAPON_SWITCHBLADE'] = {
            ['base'] = GetHashKey('COMPONENT_KNUCKLE_VARMOD_BASE'),
            ['vip'] = GetHashKey('COMPONENT_SWITCHBLADE_VARMOD_VAR1'),
            ['body'] = GetHashKey('COMPONENT_SWITCHBLADE_VARMOD_VAR2'),
        },
        -- Pistol's
        ['WEAPON_PISTOL'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_PISTOL_CLIP_02'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_PI_FLSH'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_PI_SUPP_02'),
            ['yusuf'] = GetHashKey('COMPONENT_PISTOL_VARMOD_LUXE'),
        },
        ['WEAPON_APPISTOL'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_APPISTOL_CLIP_02'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_PI_FLSH'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_PI_SUPP'),
            ['yusuf'] = GetHashKey('COMPONENT_APPISTOL_VARMOD_LUXE'),
        },
        ['WEAPON_PISTOL50'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_PISTOL50_CLIP_02'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_PI_FLSH'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_AR_SUPP_02'),
            ['yusuf'] = GetHashKey('COMPONENT_PISTOL50_VARMOD_LUXE'),
        },
        ['WEAPON_REVOLVER'] = {
            ['vip'] = GetHashKey('COMPONENT_REVOLVER_VARMOD_BOSS'),
            ['body'] = GetHashKey('COMPONENT_REVOLVER_VARMOD_GOON'),
        },
        ['WEAPON_SNSPISTOL'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_SNSPISTOL_CLIP_02'),
            ['wood'] = GetHashKey('COMPONENT_SNSPISTOL_VARMOD_LOWRIDER'),
        },
        ['WEAPON_HEAVYPISTOL'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_HEAVYPISTOL_CLIP_02'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_PI_FLSH'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_PI_SUPP'),
            ['wood'] = GetHashKey('COMPONENT_HEAVYPISTOL_VARMOD_LUXE'),
        },
        ['WEAPON_REVOLVER_MK2'] = {
            ['tracer'] = GetHashKey('COMPONENT_REVOLVER_MK2_CLIP_TRACER'),
            ['fire'] = GetHashKey('COMPONENT_REVOLVER_MK2_CLIP_INCENDIARY'),
            ['hollow'] = GetHashKey('COMPONENT_REVOLVER_MK2_CLIP_HOLLOWPOINT'),
            ['fmj'] = GetHashKey('COMPONENT_REVOLVER_MK2_CLIP_FMJ'),
            ['holo'] = GetHashKey('COMPONENT_AT_SIGHTS'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_MACRO_MK2'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_PI_FLSH'),
            ['compensator'] = GetHashKey('COMPONENT_AT_PI_COMP_03'),
            ['skin_digi'] = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO'),
            ['skin_brushstroke'] = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO_02'),
            ['skin_woodland'] = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO_03'),
            ['skin_skull'] = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO_04'),
            ['skin_sessanta'] = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO_05'),
            ['skin_perseus'] = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO_06'),
            ['skin_leopard'] = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO_07'),
            ['skin_zebra'] = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO_08'),
            ['skin_geometric'] = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO_09'),
            ['skin_boom'] = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO_10'),
            ['skin_patriotic'] = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO_IND_01'),
        },
        ['WEAPON_SNSPISTOL_MK2'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_SNSPISTOL_MK2_CLIP_02'),
            ['tracer'] = GetHashKey('COMPONENT_SNSPISTOL_MK2_CLIP_TRACER'),
            ['fire'] = GetHashKey('COMPONENT_SNSPISTOL_MK2_CLIP_INCENDIARY'),
            ['hollow'] = GetHashKey('COMPONENT_SNSPISTOL_MK2_CLIP_HOLLOWPOINT'),
            ['fmj'] = GetHashKey('COMPONENT_SNSPISTOL_MK2_CLIP_FMJ'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_PI_FLSH_03'),
            ['scope'] = GetHashKey('COMPONENT_AT_PI_RAIL_02'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_PI_SUPP_02'),
            ['compensator'] = GetHashKey('COMPONENT_AT_PI_COMP_02'),
            ['skin_digi'] = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO'),
            ['skin_brushstroke'] = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO_02'),
            ['skin_woodland'] = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO_03'),
            ['skin_skull'] = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO_04'),
            ['skin_sessanta'] = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO_05'),
            ['skin_perseus'] = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO_06'),
            ['skin_leopard'] = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO_07'),
            ['skin_zebra'] = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO_08'),
            ['skin_geometric'] = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO_09'),
            ['skin_boom'] = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO_10'),
            ['skin_patriotic'] = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO_IND_01'),
        },
        ['WEAPON_PISTOL_MK2'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_PISTOL_MK2_CLIP_02'),
            ['tracer'] = GetHashKey('COMPONENT_PISTOL_MK2_CLIP_TRACER'),
            ['fire'] = GetHashKey('COMPONENT_PISTOL_MK2_CLIP_INCENDIARY'),
            ['hollow'] = GetHashKey('COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT'),
            ['fmj'] = GetHashKey('COMPONENT_PISTOL_MK2_CLIP_FMJ'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_PI_FLSH_02'),
            ['scope'] = GetHashKey('COMPONENT_AT_PI_RAIL'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_PI_SUPP_02'),
            ['compensator'] = GetHashKey('COMPONENT_AT_PI_COMP'),
            ['skin_digi'] = GetHashKey('COMPONENT_PISTOL_MK2_CAMO'),
            ['skin_brushstroke'] = GetHashKey('COMPONENT_PISTOL_MK2_CAMO_02'),
            ['skin_woodland'] = GetHashKey('COMPONENT_PISTOL_MK2_CAMO_03'),
            ['skin_skull'] = GetHashKey('COMPONENT_PISTOL_MK2_CAMO_04'),
            ['skin_sessanta'] = GetHashKey('COMPONENT_PISTOL_MK2_CAMO_05'),
            ['skin_perseus'] = GetHashKey('COMPONENT_PISTOL_MK2_CAMO_06'),
            ['skin_leopard'] = GetHashKey('COMPONENT_PISTOL_MK2_CAMO_07'),
            ['skin_zebra'] = GetHashKey('COMPONENT_PISTOL_MK2_CAMO_08'),
            ['skin_geometric'] = GetHashKey('COMPONENT_PISTOL_MK2_CAMO_09'),
            ['skin_boom'] = GetHashKey('COMPONENT_PISTOL_MK2_CAMO_10'),
            ['skin_patriotic'] = GetHashKey('COMPONENT_PISTOL_MK2_CAMO_IND_01'),
        },
        ['WEAPON_VINTAGEPISTOL'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_VINTAGEPISTOL_CLIP_02'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_PI_SUPP')
        },
        ['WEAPON_RAYPISTOL'] = {
            ['xmas'] = GetHashKey('COMPONENT_RAYPISTOL_VARMOD_XMAS18')
        },
        ['WEAPON_CERAMICPISTOL'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_CERAMICPISTOL_CLIP_02'),
            ['suppressor'] = GetHashKey('COMPONENT_CERAMICPISTOL_SUPP')
        },
        ['WEAPON_MICROSMG'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_MICROSMG_CLIP_02'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_PI_FLSH'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_MACRO'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_AR_SUPP_02'),
            ['yusuf'] = GetHashKey('COMPONENT_MICROSMG_VARMOD_LUXE'),
        },
        ['WEAPON_SMG'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_SMG_CLIP_02'),
            ['drum_clip'] = GetHashKey('COMPONENT_SMG_CLIP_03'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_MACRO_02'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_PI_SUPP'),
            ['yusuf'] = GetHashKey('COMPONENT_SMG_VARMOD_LUXE')
        },
        ['WEAPON_ASSAULTSMG'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_ASSAULTSMG_CLIP_02'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_MACRO'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_AR_SUPP_02'),
            ['yusuf'] = GetHashKey('COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER')
        },
        ['WEAPON_MINISMG'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_MINISMG_CLIP_02')
        },
        ['WEAPON_SMG_MK2'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_SMG_MK2_CLIP_02'),
            ['tracer'] = GetHashKey('COMPONENT_SMG_MK2_CLIP_TRACER'),
            ['fire'] = GetHashKey('COMPONENT_SMG_MK2_CLIP_INCENDIARY'),
            ['hollow'] = GetHashKey('COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT'),
            ['fmj'] = GetHashKey('COMPONENT_SMG_MK2_CLIP_FMJ'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['holo'] = GetHashKey('COMPONENT_AT_SIGHTS_SMG'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2'),
            ['scope2'] = GetHashKey('COMPONENT_AT_SCOPE_SMALL_SMG_MK2'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_PI_SUPP'),
            ['muzzle'] = GetHashKey('COMPONENT_AT_MUZZLE_01'),
            ['muzzle2'] = GetHashKey('COMPONENT_AT_MUZZLE_02'),
            ['muzzle3'] = GetHashKey('COMPONENT_AT_MUZZLE_03'),
            ['muzzle4'] = GetHashKey('COMPONENT_AT_MUZZLE_04'),
            ['muzzle5'] = GetHashKey('COMPONENT_AT_MUZZLE_05'),
            ['muzzle6'] = GetHashKey('COMPONENT_AT_MUZZLE_06'),
            ['muzzle7'] = GetHashKey('COMPONENT_AT_MUZZLE_07'),
            ['barrel'] = GetHashKey('COMPONENT_AT_SB_BARREL_01'),
            ['barrel2'] = GetHashKey('COMPONENT_AT_SB_BARREL_02'),
            ['skin_digi'] = GetHashKey('COMPONENT_SMG_MK2_CAMO'),
            ['skin_brushstroke'] = GetHashKey('COMPONENT_SMG_MK2_CAMO_02'),
            ['skin_woodland'] = GetHashKey('COMPONENT_SMG_MK2_CAMO_03'),
            ['skin_skull'] = GetHashKey('COMPONENT_SMG_MK2_CAMO_04'),
            ['skin_sessanta'] = GetHashKey('COMPONENT_SMG_MK2_CAMO_05'),
            ['skin_perseus'] = GetHashKey('COMPONENT_SMG_MK2_CAMO_06'),
            ['skin_leopard'] = GetHashKey('COMPONENT_SMG_MK2_CAMO_07'),
            ['skin_zebra'] = GetHashKey('COMPONENT_SMG_MK2_CAMO_08'),
            ['skin_geometric'] = GetHashKey('COMPONENT_SMG_MK2_CAMO_09'),
            ['skin_boom'] = GetHashKey('COMPONENT_SMG_MK2_CAMO_10'),
            ['skin_patriotic'] = GetHashKey('COMPONENT_SMG_MK2_CAMO_IND_01'),
        },
        ['WEAPON_MACHINEPISTOL'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_MACHINEPISTOL_CLIP_02'),
            ['drum_clip'] = GetHashKey('COMPONENT_MACHINEPISTOL_CLIP_03'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_PI_SUPP')
        },
        ['WEAPON_COMBATPDW'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_COMBATPDW_CLIP_02'),
            ['drum_clip'] = GetHashKey('COMPONENT_COMBATPDW_CLIP_03'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['grip'] = GetHashKey('COMPONENT_AT_AR_AFGRIP'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_SMALL')
        },
        ['WEAPON_PUMPSHOTGUN'] = {
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_SR_SUPP'),
            ['yusuf'] = GetHashKey('COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER')
        },
        ['WEAPON_SAWNOFFSHOTGUN'] = {
            ['metal'] = GetHashKey('COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE')
        },
        ['WEAPON_ASSAULTSHOTGUN'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_ASSAULTSHOTGUN_CLIP_02'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_AR_SUPP'),
            ['grip'] = GetHashKey('COMPONENT_AT_AR_AFGRIP')
        },
        ['WEAPON_BULLPUPSHOTGUN'] = {
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_AR_SUPP_02'),
            ['grip'] = GetHashKey('COMPONENT_AT_AR_AFGRIP')
        },
        ['WEAPON_PUMPSHOTGUN_MK2'] = {
            ['fire'] = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY'),
            ['armor'] = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CLIP_ARMORPIERCING'),
            ['hollow'] = GetHashKey('COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT'),
            ['explosive'] = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE'),
            ['holo'] = GetHashKey('COMPONENT_AT_SIGHTS'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_MACRO_MK2'),
            ['scope2'] = GetHashKey('COMPONENT_AT_SCOPE_SMALL_MK2'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_SR_SUPP_03'),
            ['muzzle'] = GetHashKey('COMPONENT_AT_MUZZLE_08'),
            ['skin_digi'] = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO'),
            ['skin_brushstroke'] = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO_02'),
            ['skin_woodland'] = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO_03'),
            ['skin_skull'] = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO_04'),
            ['skin_sessanta'] = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO_05'),
            ['skin_perseus'] = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO_06'),
            ['skin_leopard'] = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO_07'),
            ['skin_zebra'] = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO_08'),
            ['skin_geometric'] = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO_09'),
            ['skin_boom'] = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO_10'),
            ['skin_patriotic'] = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01'),
        },
        ['WEAPON_HEAVYSHOTGUN'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_HEAVYSHOTGUN_CLIP_02'),
            ['drum_clip'] = GetHashKey('COMPONENT_HEAVYSHOTGUN_CLIP_03'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_AR_SUPP_02'),
            ['grip'] = GetHashKey('COMPONENT_AT_AR_AFGRIP')
        },
        ['WEAPON_COMBATSHOTGUN'] = {
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_AR_SUPP')
        },
        ['WEAPON_ASSAULTRIFLE'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_ASSAULTRIFLE_CLIP_02'),
            ['drum_clip'] = GetHashKey('COMPONENT_ASSAULTRIFLE_CLIP_03'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_MACRO'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_AR_SUPP_02'),
            ['grip'] = GetHashKey('COMPONENT_AT_AR_AFGRIP'),
            ['yusuf'] = GetHashKey('COMPONENT_ASSAULTRIFLE_VARMOD_LUXE'),
        },
        ['WEAPON_CARBINERIFLE'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_CARBINERIFLE_CLIP_02'),
            ['drum_clip'] = GetHashKey('COMPONENT_CARBINERIFLE_CLIP_03'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_MEDIUM'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_AR_SUPP'),
            ['grip'] = GetHashKey('COMPONENT_AT_AR_AFGRIP'),
            ['yusuf'] = GetHashKey('COMPONENT_CARBINERIFLE_VARMOD_LUXE'),
        },
        ['WEAPON_CARBINERIFLE'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_ADVANCEDRIFLE_CLIP_02'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_SMALL'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_AR_SUPP'),
            ['metal'] = GetHashKey('COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE'),
        },
        ['WEAPON_SPECIALCARBINE'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_SPECIALCARBINE_CLIP_02'),
            ['drum_clip'] = GetHashKey('COMPONENT_SPECIALCARBINE_CLIP_03'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_MEDIUM'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_AR_SUPP_02'),
            ['grip'] = GetHashKey('COMPONENT_AT_AR_AFGRIP'),
            ['metal'] = GetHashKey('COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER'),
        },
        ['WEAPON_BULLPUPRIFLE'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_BULLPUPRIFLE_CLIP_02'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_SMALL'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_AR_SUPP'),
            ['grip'] = GetHashKey('COMPONENT_AT_AR_AFGRIP'),
            ['metal'] = GetHashKey('COMPONENT_BULLPUPRIFLE_VARMOD_LOW'),
        },
        ['WEAPON_BULLPUPRIFLE_MK2'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CLIP_02'),
            ['tracer'] = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CLIP_TRACER'),
            ['fire'] = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CLIP_INCENDIARY'),
            ['armor'] = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CLIP_ARMORPIERCING'),
            ['fmj'] = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['holo'] = GetHashKey('COMPONENT_AT_SIGHTS'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_MACRO_02_MK2'),
            ['scope2'] = GetHashKey('COMPONENT_AT_SCOPE_SMALL_MK2'),
            ['barrel'] = GetHashKey('COMPONENT_AT_BP_BARREL_01'),
            ['barrel2'] = GetHashKey('COMPONENT_AT_BP_BARREL_02'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_AR_SUPP'),
            ['grip'] = GetHashKey('COMPONENT_AT_AR_AFGRIP_02'),
            ['muzzle'] = GetHashKey('COMPONENT_AT_MUZZLE_01'),
            ['muzzle2'] = GetHashKey('COMPONENT_AT_MUZZLE_02'),
            ['muzzle3'] = GetHashKey('COMPONENT_AT_MUZZLE_03'),
            ['muzzle4'] = GetHashKey('COMPONENT_AT_MUZZLE_04'),
            ['muzzle5'] = GetHashKey('COMPONENT_AT_MUZZLE_05'),
            ['muzzle6'] = GetHashKey('COMPONENT_AT_MUZZLE_06'),
            ['muzzle7'] = GetHashKey('COMPONENT_AT_MUZZLE_07'),
            ['skin_digi'] = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO'),
            ['skin_brushstroke'] = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO_02'),
            ['skin_woodland'] = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO_03'),
            ['skin_skull'] = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO_04'),
            ['skin_sessanta'] = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO_05'),
            ['skin_perseus'] = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO_06'),
            ['skin_leopard'] = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO_07'),
            ['skin_zebra'] = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO_08'),
            ['skin_geometric'] = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO_09'),
            ['skin_boom'] = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO_10'),
            ['skin_patriotic'] = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01'),
        },
        ['WEAPON_SPECIALCARBINE_MK2'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CLIP_02'),
            ['tracer'] = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CLIP_TRACER'),
            ['fire'] = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CLIP_INCENDIARY'),
            ['armor'] = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CLIP_ARMORPIERCING'),
            ['fmj'] = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['holo'] = GetHashKey('COMPONENT_AT_SIGHTS'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_MACRO_MK2'),
            ['scope2'] = GetHashKey('COMPONENT_AT_SCOPE_MEDIUM_MK2'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_AR_SUPP_02'),
            ['muzzle'] = GetHashKey('COMPONENT_AT_MUZZLE_01'),
            ['muzzle2'] = GetHashKey('COMPONENT_AT_MUZZLE_02'),
            ['muzzle3'] = GetHashKey('COMPONENT_AT_MUZZLE_03'),
            ['muzzle4'] = GetHashKey('COMPONENT_AT_MUZZLE_04'),
            ['muzzle5'] = GetHashKey('COMPONENT_AT_MUZZLE_05'),
            ['muzzle6'] = GetHashKey('COMPONENT_AT_MUZZLE_06'),
            ['muzzle7'] = GetHashKey('COMPONENT_AT_MUZZLE_07'),
            ['grip'] = GetHashKey('COMPONENT_AT_AR_AFGRIP_02'),
            ['barrel'] = GetHashKey('COMPONENT_AT_SC_BARREL_01'),
            ['barrel2'] = GetHashKey('COMPONENT_AT_SC_BARREL_02'),
            ['skin_digi'] = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO'),
            ['skin_brushstroke'] = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO_02'),
            ['skin_woodland'] = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO_03'),
            ['skin_skull'] = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO_04'),
            ['skin_sessanta'] = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO_05'),
            ['skin_perseus'] = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO_06'),
            ['skin_leopard'] = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO_07'),
            ['skin_zebra'] = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO_08'),
            ['skin_geometric'] = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO_09'),
            ['skin_boom'] = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO_10'),
            ['skin_patriotic'] = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01'),
        },
        ['WEAPON_ASSAULTRIFLE_MK2'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CLIP_02'),
            ['tracer'] = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER'),
            ['fire'] = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY'),
            ['armor'] = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING'),
            ['fmj'] = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ'),
            ['grip'] = GetHashKey('COMPONENT_AT_AR_AFGRIP_02'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['holo'] = GetHashKey('COMPONENT_AT_SIGHTS'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_MACRO_MK2'),
            ['scope2'] = GetHashKey('COMPONENT_AT_SCOPE_MEDIUM_MK2'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_AR_SUPP_02'),
            ['muzzle'] = GetHashKey('COMPONENT_AT_MUZZLE_01'),
            ['muzzle2'] = GetHashKey('COMPONENT_AT_MUZZLE_02'),
            ['muzzle3'] = GetHashKey('COMPONENT_AT_MUZZLE_03'),
            ['muzzle4'] = GetHashKey('COMPONENT_AT_MUZZLE_04'),
            ['muzzle5'] = GetHashKey('COMPONENT_AT_MUZZLE_05'),
            ['muzzle6'] = GetHashKey('COMPONENT_AT_MUZZLE_06'),
            ['muzzle7'] = GetHashKey('COMPONENT_AT_MUZZLE_07'),
            ['barrel'] = GetHashKey('COMPONENT_AT_AR_BARREL_01'),
            ['barrel2'] = GetHashKey('COMPONENT_AT_AR_BARREL_02'),
            ['skin_digi'] = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO'),
            ['skin_brushstroke'] = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO_02'),
            ['skin_woodland'] = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO_03'),
            ['skin_skull'] = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO_04'),
            ['skin_sessanta'] = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO_05'),
            ['skin_perseus'] = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO_06'),
            ['skin_leopard'] = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO_07'),
            ['skin_zebra'] = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO_08'),
            ['skin_geometric'] = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO_09'),
            ['skin_boom'] = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO_10'),
            ['skin_patriotic'] = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01'),
        },
        ['WEAPON_CARBINERIFLE_MK2'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CLIP_02'),
            ['tracer'] = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER'),
            ['fire'] = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY'),
            ['armor'] = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING'),
            ['fmj'] = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ'),
            ['grip'] = GetHashKey('COMPONENT_AT_AR_AFGRIP_02'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['holo'] = GetHashKey('COMPONENT_AT_SIGHTS'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_MACRO_MK2'),
            ['scope2'] = GetHashKey('COMPONENT_AT_SCOPE_MEDIUM_MK2'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_AR_SUPP'),
            ['muzzle'] = GetHashKey('COMPONENT_AT_MUZZLE_01'),
            ['muzzle2'] = GetHashKey('COMPONENT_AT_MUZZLE_02'),
            ['muzzle3'] = GetHashKey('COMPONENT_AT_MUZZLE_03'),
            ['muzzle4'] = GetHashKey('COMPONENT_AT_MUZZLE_04'),
            ['muzzle5'] = GetHashKey('COMPONENT_AT_MUZZLE_05'),
            ['muzzle6'] = GetHashKey('COMPONENT_AT_MUZZLE_06'),
            ['muzzle7'] = GetHashKey('COMPONENT_AT_MUZZLE_07'),
            ['barrel'] = GetHashKey('COMPONENT_AT_CR_BARREL_01'),
            ['barrel2'] = GetHashKey('COMPONENT_AT_CR_BARREL_02'),
            ['skin_digi'] = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO'),
            ['skin_brushstroke'] = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO_02'),
            ['skin_woodland'] = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO_03'),
            ['skin_skull'] = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO_04'),
            ['skin_sessanta'] = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO_05'),
            ['skin_perseus'] = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO_06'),
            ['skin_leopard'] = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO_07'),
            ['skin_zebra'] = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO_08'),
            ['skin_geometric'] = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO_09'),
            ['skin_boom'] = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO_10'),
            ['skin_patriotic'] = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01'),
        },
        ['WEAPON_COMPACTRIFLE'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_COMPACTRIFLE_CLIP_02'),
            ['drum_clip'] = GetHashKey('COMPONENT_COMPACTRIFLE_CLIP_03')
        },
        ['WEAPON_MILITARYRIFLE'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_MILITARYRIFLE_CLIP_02'),
            ['sight'] = GetHashKey('COMPONENT_MILITARYRIFLE_SIGHT_01'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_SMALL'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_AR_SUPP')
        },
        ['WEAPON_MG'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_MG_CLIP_02'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_SMALL_02'),
            ['yusuf'] = GetHashKey('COMPONENT_MG_VARMOD_LOWRIDER')
        },
        ['WEAPON_COMBATMG'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_COMBATMG_CLIP_02'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_MEDIUM'),
            ['grip'] = GetHashKey('COMPONENT_AT_AR_AFGRIP'),
            ['metal'] = GetHashKey('COMPONENT_COMBATMG_VARMOD_LOWRIDER')
        },
        ['WEAPON_COMBATMG_MK2'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_COMBATMG_CLIP_02'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_MEDIUM'),
            ['grip'] = GetHashKey('COMPONENT_AT_AR_AFGRIP'),
            ['metal'] = GetHashKey('COMPONENT_COMBATMG_VARMOD_LOWRIDER')
        },
        ['WEAPON_GUSENBERG'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_GUSENBERG_CLIP_02')
        },
        ['WEAPON_COMBATMG_MK2'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_COMBATMG_MK2_CLIP_02'),
            ['tracer'] = GetHashKey('COMPONENT_COMBATMG_MK2_CLIP_TRACER'),
            ['fire'] = GetHashKey('COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY'),
            ['armor'] = GetHashKey('COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING'),
            ['fmj'] = GetHashKey('COMPONENT_COMBATMG_MK2_CLIP_FMJ'),
            ['grip'] = GetHashKey('COMPONENT_AT_AR_AFGRIP_02'),
            ['holo'] = GetHashKey('COMPONENT_AT_SIGHTS'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_SMALL_MK2'),
            ['scope2'] = GetHashKey('COMPONENT_AT_SCOPE_MEDIUM_MK2'),
            ['muzzle'] = GetHashKey('COMPONENT_AT_MUZZLE_01'),
            ['muzzle2'] = GetHashKey('COMPONENT_AT_MUZZLE_02'),
            ['muzzle3'] = GetHashKey('COMPONENT_AT_MUZZLE_03'),
            ['muzzle4'] = GetHashKey('COMPONENT_AT_MUZZLE_04'),
            ['muzzle5'] = GetHashKey('COMPONENT_AT_MUZZLE_05'),
            ['muzzle6'] = GetHashKey('COMPONENT_AT_MUZZLE_06'),
            ['muzzle7'] = GetHashKey('COMPONENT_AT_MUZZLE_07'),
            ['barrel'] = GetHashKey('COMPONENT_AT_MG_BARREL_01'),
            ['barrel2'] = GetHashKey('COMPONENT_AT_MG_BARREL_02'),
            ['skin_digi'] = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO'),
            ['skin_brushstroke'] = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO_02'),
            ['skin_woodland'] = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO_03'),
            ['skin_skull'] = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO_04'),
            ['skin_sessanta'] = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO_05'),
            ['skin_perseus'] = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO_06'),
            ['skin_leopard'] = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO_07'),
            ['skin_zebra'] = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO_08'),
            ['skin_geometric'] = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO_09'),
            ['skin_boom'] = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO_10'),
            ['skin_patriotic'] = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO_IND_01'),
        },
        ['WEAPON_SNIPERRIFLE'] = {
            ['suppressor'] = GetHashKey('COMPONENT_AT_AR_SUPP_02'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_LARGE'),
            ['scope2'] = GetHashKey('COMPONENT_AT_SCOPE_MAX'),
            ['wood'] = GetHashKey('COMPONENT_SNIPERRIFLE_VARMOD_LUXE')
        },
        ['WEAPON_HEAVYSNIPER'] = {
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_LARGE'),
            ['scope2'] = GetHashKey('COMPONENT_AT_SCOPE_MAX')
        },
        ['WEAPON_MARKSMANRIFLE_MK2'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CLIP_02'),
            ['tracer'] = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CLIP_TRACER'),
            ['fire'] = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CLIP_INCENDIARY'),
            ['armor'] = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CLIP_ARMORPIERCING'),
            ['fmj'] = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ'),
            ['holo'] = GetHashKey('COMPONENT_AT_SIGHTS'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_MEDIUM_MK2'),
            ['scope2'] = GetHashKey('COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_AR_SUPP'),
            ['muzzle'] = GetHashKey('COMPONENT_AT_MUZZLE_01'),
            ['muzzle2'] = GetHashKey('COMPONENT_AT_MUZZLE_02'),
            ['muzzle3'] = GetHashKey('COMPONENT_AT_MUZZLE_03'),
            ['muzzle4'] = GetHashKey('COMPONENT_AT_MUZZLE_04'),
            ['muzzle5'] = GetHashKey('COMPONENT_AT_MUZZLE_05'),
            ['muzzle6'] = GetHashKey('COMPONENT_AT_MUZZLE_06'),
            ['muzzle7'] = GetHashKey('COMPONENT_AT_MUZZLE_07'),
            ['barrel'] = GetHashKey('COMPONENT_AT_MRFL_BARREL_01'),
            ['barrel2'] = GetHashKey('COMPONENT_AT_MRFL_BARREL_02'),
            ['grip'] = GetHashKey('COMPONENT_AT_AR_AFGRIP_02'),
            ['skin_digi'] = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO'),
            ['skin_brushstroke'] = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO_02'),
            ['skin_woodland'] = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO_03'),
            ['skin_skull'] = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO_04'),
            ['skin_sessanta'] = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO_05'),
            ['skin_perseus'] = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO_06'),
            ['skin_leopard'] = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO_07'),
            ['skin_zebra'] = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO_08'),
            ['skin_geometric'] = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO_09'),
            ['skin_boom'] = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO_10'),
            ['skin_patriotic'] = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01'),
        },
        ['WEAPON_HEAVYSNIPER_MK2'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CLIP_02'),
            ['tracer'] = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CLIP_TRACER'),
            ['fire'] = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY'),
            ['armor'] = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING'),
            ['fmj'] = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ'),
            ['explosive'] = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_LARGE_MK2'),
            ['scope2'] = GetHashKey('COMPONENT_AT_SCOPE_MAX'),
            ['scope3'] = GetHashKey('COMPONENT_AT_SCOPE_NV'),
            ['scope4'] = GetHashKey('COMPONENT_AT_SCOPE_THERMAL'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_SR_SUPP_03'),
            ['muzzle'] = GetHashKey('COMPONENT_AT_MUZZLE_08'),
            ['muzzle2'] = GetHashKey('COMPONENT_AT_MUZZLE_09'),
            ['barrel'] = GetHashKey('COMPONENT_AT_SR_BARREL_01'),
            ['barrel2'] = GetHashKey('COMPONENT_AT_SR_BARREL_02'),
            ['skin_digi'] = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO'),
            ['skin_brushstroke'] = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO_02'),
            ['skin_woodland'] = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO_03'),
            ['skin_skull'] = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO_04'),
            ['skin_sessanta'] = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO_05'),
            ['skin_perseus'] = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO_06'),
            ['skin_leopard'] = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO_07'),
            ['skin_zebra'] = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO_08'),
            ['skin_geometric'] = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO_09'),
            ['skin_boom'] = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO_10'),
            ['skin_patriotic'] = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01'),
        },
        ['WEAPON_MARKSMANRIFLE'] = {
            ['extended_clip'] = GetHashKey('COMPONENT_MARKSMANRIFLE_CLIP_02'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM'),
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['suppressor'] = GetHashKey('COMPONENT_AT_AR_SUPP'),
            ['grip'] = GetHashKey('COMPONENT_AT_AR_AFGRIP'),
            ['yusuf'] = GetHashKey('COMPONENT_MARKSMANRIFLE_VARMOD_LUXE'),
        },
        ['WEAPON_GRENADELAUNCHER'] = {
            ['flashlight'] = GetHashKey('COMPONENT_AT_AR_FLSH'),
            ['grip'] = GetHashKey('COMPONENT_AT_AR_AFGRIP'),
            ['scope'] = GetHashKey('COMPONENT_AT_SCOPE_SMALL')
        },
    },
    HashToString = {
        -- Melee's
        [GetHashKey('WEAPON_DAGGER')] = 'WEAPON_DAGGER',
        [GetHashKey('WEAPON_BAT')] = 'WEAPON_BAT',
        [GetHashKey('WEAPON_BOTTLE')] = 'WEAPON_BOTTLE',
        [GetHashKey('WEAPON_CROWBAR')] = 'WEAPON_CROWBAR',
        [GetHashKey('WEAPON_UNARMED')] = 'WEAPON_UNARMED',
        [GetHashKey('WEAPON_FLASHLIGHT')] = 'WEAPON_FLASHLIGHT',
        [GetHashKey('WEAPON_GOLFCLUB')] = 'WEAPON_GOLFCLUB',
        [GetHashKey('WEAPON_HAMMER')] = 'WEAPON_HAMMER',
        [GetHashKey('WEAPON_HATCHET')] = 'WEAPON_HATCHET',
        [GetHashKey('WEAPON_KNUCKLE')] = 'WEAPON_KNUCKLE',
        [GetHashKey('WEAPON_KNIFE')] = 'WEAPON_KNIFE',
        [GetHashKey('WEAPON_MACHETE')] = 'WEAPON_MACHETE',
        [GetHashKey('WEAPON_SWITCHBLADE')] = 'WEAPON_SWITCHBLADE',
        [GetHashKey('WEAPON_NIGHTSTICK')] = 'WEAPON_NIGHTSTICK',
        [GetHashKey('WEAPON_WRENCH')] = 'WEAPON_WRENCH',
        [GetHashKey('WEAPON_BATTLEAXE')] = 'WEAPON_BATTLEAXE',
        [GetHashKey('WEAPON_POOLCUE')] = 'WEAPON_POOLCUE',
        [GetHashKey('WEAPON_STONE_HATCHET')] = 'WEAPON_STONE_HATCHET',
        -- Pistol's
        [GetHashKey('WEAPON_PISTOL')] = 'WEAPON_PISTOL',
        [GetHashKey('WEAPON_PISTOL_MK2')] = 'WEAPON_PISTOL_MK2',
        [GetHashKey('WEAPON_COMBATPISTOL')] = 'WEAPON_COMBATPISTOL',
        [GetHashKey('WEAPON_APPISTOL')] = 'WEAPON_APPISTOL',
        [GetHashKey('WEAPON_STUNGUN')] = 'WEAPON_STUNGUN',
        [GetHashKey('WEAPON_PISTOL50')] = 'WEAPON_PISTOL50',
        [GetHashKey('WEAPON_SNSPISTOL')] = 'WEAPON_SNSPISTOL',
        [GetHashKey('WEAPON_SNSPISTOL_MK2')] = 'WEAPON_SNSPISTOL_MK2',
        [GetHashKey('WEAPON_HEAVYPISTOL')] = 'WEAPON_HEAVYPISTOL',
        [GetHashKey('WEAPON_VINTAGEPISTOL')] = 'WEAPON_VINTAGEPISTOL',
        [GetHashKey('WEAPON_FLAREGUN')] = 'WEAPON_DAGGER',
        [GetHashKey('WEAPON_MARKSMANPISTOL')] = 'WEAPON_MARKSMANPISTOL',
        [GetHashKey('WEAPON_REVOLVER')] = 'WEAPON_REVOLVER',
        [GetHashKey('WEAPON_REVOLVER_MK2')] = 'WEAPON_REVOLVER_MK2',
        [GetHashKey('WEAPON_DOUBLEACTION')] = 'WEAPON_DOUBLEACTION',
        [GetHashKey('WEAPON_RAYPISTOL')] = 'WEAPON_RAYPISTOL',
        [GetHashKey('WEAPON_CERAMICPISTOL')] = 'WEAPON_CERAMICPISTOL',
        [GetHashKey('WEAPON_NAVYREVOLVER')] = 'WEAPON_NAVYREVOLVER',
        [GetHashKey('WEAPON_GADGETPISTOL')] = 'WEAPON_GADGETPISTOL',
        -- SMG's
        [GetHashKey('WEAPON_MICROSMG')] = 'WEAPON_MICROSMG',
        [GetHashKey('WEAPON_SMG')] = 'WEAPON_SMG',
        [GetHashKey('WEAPON_SMG_MK2')] = 'WEAPON_SMG_MK2',
        [GetHashKey('WEAPON_ASSAULTSMG')] = 'WEAPON_ASSAULTSMG',
        [GetHashKey('WEAPON_COMBATPDW')] = 'WEAPON_COMBATPDW',
        [GetHashKey('WEAPON_MACHINEPISTOL')] = 'WEAPON_MACHINEPISTOL',
        [GetHashKey('WEAPON_MINISMG')] = 'WEAPON_MINISMG',
        [GetHashKey('WEAPON_RAYCARBINE')] = 'WEAPON_RAYCARBINE',
        -- Shotgun's
        [GetHashKey('WEAPON_PUMPSHOTGUN')] = 'WEAPON_PUMPSHOTGUN',
        [GetHashKey('WEAPON_PUMPSHOTGUN_MK2')] = 'WEAPON_PUMPSHOTGUN_MK2',
        [GetHashKey('WEAPON_SAWNOFFSHOTGUN')] = 'WEAPON_SAWNOFFSHOTGUN',
        [GetHashKey('WEAPON_ASSAULTSHOTGUN')] = 'WEAPON_ASSAULTSHOTGUN',
        [GetHashKey('WEAPON_BULLPUPSHOTGUN')] = 'WEAPON_BULLPUPSHOTGUN',
        [GetHashKey('WEAPON_MUSKET')] = 'WEAPON_MUSKET',
        [GetHashKey('WEAPON_HEAVYSHOTGUN')] = 'WEAPON_HEAVYSHOTGUN',
        [GetHashKey('WEAPON_DBSHOTGUN')] = 'WEAPON_DBSHOTGUN',
        [GetHashKey('WEAPON_AUTOSHOTGUN')] = 'WEAPON_AUTOSHOTGUN',
        [GetHashKey('WEAPON_COMBATSHOTGUN')] = 'WEAPON_COMBATSHOTGUN',
        -- Rifle's
        [GetHashKey('WEAPON_ASSAULTRIFLE')] = 'WEAPON_COMBATSHOTGUN',
        [GetHashKey('WEAPON_ASSAULTRIFLE_MK2')] = 'WEAPON_ASSAULTRIFLE_MK2',
        [GetHashKey('WEAPON_CARBINERIFLE')] = 'WEAPON_CARBINERIFLE',
        [GetHashKey('WEAPON_CARBINERIFLE_MK2')] = 'WEAPON_CARBINERIFLE_MK2',
        [GetHashKey('WEAPON_ADVANCEDRIFLE')] = 'WEAPON_ADVANCEDRIFLE',
        [GetHashKey('WEAPON_SPECIALCARBINE')] = 'WEAPON_SPECIALCARBINE',
        [GetHashKey('WEAPON_SPECIALCARBINE_MK2')] = 'WEAPON_SPECIALCARBINE_MK2',
        [GetHashKey('WEAPON_BULLPUPRIFLE')] = 'WEAPON_BULLPUPRIFLE',
        [GetHashKey('WEAPON_BULLPUPRIFLE_MK2')] = 'WEAPON_BULLPUPRIFLE_MK2',
        [GetHashKey('WEAPON_COMPACTRIFLE')] = 'WEAPON_COMPACTRIFLE',
        [GetHashKey('WEAPON_MILITARYRIFLE')] = 'WEAPON_MILITARYRIFLE',
        [GetHashKey('WEAPON_HEAVYRIFLE')] = 'WEAPON_HEAVYRIFLE',
        [GetHashKey('WEAPON_TACTICALRIFLE')] = 'WEAPON_TACTICALRIFLE',
        -- MG's
        [GetHashKey('WEAPON_MG')] = 'WEAPON_MG',
        [GetHashKey('WEAPON_COMBATMG')] = 'WEAPON_COMBATMG',
        [GetHashKey('WEAPON_COMBATMG_MK2')] = 'WEAPON_COMBATMG_MK2',
        [GetHashKey('WEAPON_GUSENBERG')] = 'WEAPON_GUSENBERG',
        -- Sniper's
        [GetHashKey('WEAPON_SNIPERRIFLE')] = 'WEAPON_SNIPERRIFLE',
        [GetHashKey('WEAPON_HEAVYSNIPER')] = 'WEAPON_HEAVYSNIPER',
        [GetHashKey('WEAPON_HEAVYSNIPER_MK2')] = 'WEAPON_HEAVYSNIPER_MK2',
        [GetHashKey('WEAPON_MARKSMANRIFLE')] = 'WEAPON_MARKSMANRIFLE',
        [GetHashKey('WEAPON_MARKSMANRIFLE_MK2')] = 'WEAPON_MARKSMANRIFLE_MK2',
        [GetHashKey('WEAPON_PRECISIONRIFLE')] = 'WEAPON_PRECISIONRIFLE',
        -- Heavies
        [GetHashKey('WEAPON_RPG')] = 'WEAPON_RPG',
        [GetHashKey('WEAPON_GRENADELAUNCHER')] = 'WEAPON_GRENADELAUNCHER',
        [GetHashKey('WEAPON_GRENADELAUNCHER_SMOKE')] = 'WEAPON_GRENADELAUNCHER_SMOKE',
        [GetHashKey('WEAPON_MINIGUN')] = 'WEAPON_MINIGUN',
        [GetHashKey('WEAPON_FIREWORK')] = 'WEAPON_FIREWORK',
        [GetHashKey('WEAPON_RAILGUN')] = 'WEAPON_RAILGUN',
        [GetHashKey('WEAPON_HOMINGLAUNCHER')] = 'WEAPON_HOMINGLAUNCHER',
        [GetHashKey('WEAPON_COMPACTLAUNCHER')] = 'WEAPON_COMPACTLAUNCHER',
        [GetHashKey('WEAPON_RAYMINIGUN')] = 'WEAPON_RAYMINIGUN',
        [GetHashKey('WEAPON_EMPLAUNCHER')] = 'WEAPON_EMPLAUNCHER',
        -- Throwables
        [GetHashKey('WEAPON_GRENADE')] = 'WEAPON_GRENADE',
        [GetHashKey('WEAPON_BZGAS')] = 'WEAPON_BZGAS',
        [GetHashKey('WEAPON_MOLOTOV')] = 'WEAPON_MOLOTOV',
        [GetHashKey('WEAPON_STICKYBOMB')] = 'WEAPON_STICKYBOMB',
        [GetHashKey('WEAPON_PROXMINE')] = 'WEAPON_PROXMINE',
        [GetHashKey('WEAPON_SNOWBALL')] = 'WEAPON_SNOWBALL',
        [GetHashKey('WEAPON_PIPEBOMB')] = 'WEAPON_PIPEBOMB',
        [GetHashKey('WEAPON_BALL')] = 'WEAPON_BALL',
        [GetHashKey('WEAPON_SMOKEGRENADE')] = 'WEAPON_SMOKEGRENADE',
        [GetHashKey('WEAPON_FLARE')] = 'WEAPON_FLARE',
        -- Other's
        [GetHashKey('WEAPON_PETROLCAN')] = 'WEAPON_PETROLCAN',
        [GetHashKey('GADGET_PARACHUTE')] = 'GADGET_PARACHUTE',
        [GetHashKey('WEAPON_FIREEXTINGUISHER')] = 'WEAPON_FIREEXTINGUISHER',
    },
    MetaData = {
        ['WEAPON_KNUCKLE'] = { label = 'SCHLAGRING', type = 'NAHKAMPF' },
        ['WEAPON_SWITCHBLADE'] = { label = 'KLAPPMESSER', type = 'NAHKAMPF' },
        ['WEAPON_PISTOL'] = { label = 'PISTOLE', type = 'KURZWAFFE' },
        ['WEAPON_APPISTOL'] = { label = 'AP PISTOLE', type = 'KURZWAFFE' },
        ['WEAPON_PISTOL50'] = { label = 'PISTOLE .50', type = 'KURZWAFFE' },
        ['WEAPON_REVOLVER'] = { label = 'REVOLVER', type = 'KURZWAFFE' },
        ['WEAPON_SNSPISTOL'] = { label = 'BILLIG KNARRE', type = 'KURZWAFFE' },
        ['WEAPON_HEAVYPISTOL'] = { label = 'SCHWERE PISTOLE', type = 'KURZWAFFE' },
        ['WEAPON_REVOLVER_MK2'] = { label = 'REVOLVER MKII', type = 'KURZWAFFE' },
        ['WEAPON_SNSPISTOL_MK2'] = { label = 'BILLIG KNARRE MKII', type = 'KURZWAFFE' },
        ['WEAPON_PISTOL_MK2'] = { label = 'PISTOLE MKII', type = 'KURZWAFFE' },
        ['WEAPON_VINTAGEPISTOL'] = { label = 'KLASSISCHE PISTOLE', type = 'KURZWAFFE' },
        ['WEAPON_RAYPISTOL'] = { label = 'STRAHLENPISTOLE', type = 'KURZWAFFE' },
        ['WEAPON_CERAMICPISTOL'] = { label = 'KERAMIK PISTOLE', type = 'KURZWAFFE' },
        ['WEAPON_MICROSMG'] = { label = 'MIKRO MP', type = 'MASCHINENPISTOLE' },
        ['WEAPON_SMG'] = { label = 'MP', type = 'MASCHINENPISTOLE' },
        ['WEAPON_ASSAULTSMG'] = { label = 'STURM-MP', type = 'MP' },
        ['WEAPON_MINISMG'] = { label = 'MINI-MP', type = 'MP' },
        ['WEAPON_SMG_MK2'] = { label = 'MP MKII', type = 'MP' },
        ['WEAPON_MACHINEPISTOL'] = { label = 'REIHENFEUERPISTOLE', type = 'MP' },
        ['WEAPON_COMBATPDW'] = { label = 'EINSATZ-PDW', type = 'MP' },
        ['WEAPON_PUMPSHOTGUN'] = { label = 'SCHROTFLINTE', type = 'SCHROTFLINTE' },
        ['WEAPON_SAWNOFFSHOTGUN'] = { label = 'ABG. SCHROTFLINTE', type = 'SCHROTFLINTE' },
        ['WEAPON_ASSAULTSHOTGUN'] = { label = 'STURM-SCHROTFLINTE', type = 'SCHROTFLINTE' },
        ['WEAPON_BULLPUPSHOTGUN'] = { label = 'BULLPUP SCHROTFLINTE', type = 'SCHROTFLINTE' },
        ['WEAPON_PUMPSHOTGUN_MK2'] = { label = 'SCHROTFLINTE MKII', type = 'SCHROTFLINTE' },
        ['WEAPON_HEAVYSHOTGUN'] = { label = 'SCHWERE SCHROTFLINTE', type = 'SCHROTFLINTE' },
        ['WEAPON_COMBATSHOTGUN'] = { label = 'KAMPF SCHROTFLINTE', type = 'SCHROTFLINTE' },
        ['WEAPON_ASSAULTRIFLE'] = { label = 'STURMGEWEHR', type = 'LANGWAFFE' },
        ['WEAPON_CARBINERIFLE'] = { label = 'KARABINER', type = 'LANGWAFFE' },
        ['WEAPON_SPECIALCARBINE'] = { label = 'SPEZIALKARABINER', type = 'LANGWAFFE' },
        ['WEAPON_BULLPUPRIFLE'] = { label = 'BULLPUP-GEWEHR', type = 'LANGWAFFE' },
        ['WEAPON_BULLPUPRIFLE_MK2'] = { label = 'BULLPUP-GEWEHR MKII', type = 'LANGWAFFE' },
        ['WEAPON_SPECIALCARBINE_MK2'] = { label = 'SPEZIALKARABINER MKII', type = 'LANGWAFFE' },
        ['WEAPON_ASSAULTRIFLE_MK2'] = { label = 'STURMGEWEHR MKII', type = 'LANGWAFFE' },
        ['WEAPON_CARBINERIFLE_MK2'] = { label = 'KARABINER MKII', type = 'LANGWAFFE' },
        ['WEAPON_COMPACTRIFLE'] = { label = 'KOMPAKTES GEWEHR', type = 'LANGWAFFE' },
        ['WEAPON_MILITARYRIFLE'] = { label = 'MILITÄRGEWEHR', type = 'LANGWAFFE' },
        ['WEAPON_MG'] = { label = 'MASCHINENGEWEHR', type = 'MASCHINENGEWEHR' },
        ['WEAPON_COMBATMG'] = { label = 'GEFECHTSMG', type = 'MASCHINENGEWEHR' },
        ['WEAPON_COMBATMG_MK2'] = { label = 'GEFECHTSMG MKII', type = 'MASCHINENGEWEHR' },
        ['WEAPON_GUSENBERG'] = { label = 'GUSENBERG', type = 'MASCHINENGEWEHR' },
        ['WEAPON_SNIPERRIFLE'] = { label = 'SCHARFSCHÜTZENGEWEHR', type = 'SCHARFSCHÜTZENGEWEHR' },
        ['WEAPON_HEAVYSNIPER'] = { label = 'SCHWERES SCHARFSCHÜTZENGEWEHR', type = 'SCHARFSCHÜTZENGEWEHR' },
        ['WEAPON_MARKSMANRIFLE_MK2'] = { label = 'PRÄZISIONSGEWEHR MKII', type = 'SCHARFSCHÜTZENGEWEHR' },
        ['WEAPON_HEAVYSNIPER_MK2'] = { label = 'SCHWERES SCHARFSCHÜTZENGEWEHR MKII', type = 'SCHARFSCHÜTZENGEWEHR' },
        ['WEAPON_MARKSMANRIFLE'] = { label = 'PRÄZISIONSGEWEHR', type = 'SCHARFSCHÜTZENGEWEHR' }
    },
    ClothingTypes = {
        ['mask'] = {
            Component = 1,
            Label = 'Maske',
            name = 'mask',
            icon = 'images/clothingTypes/mask.png'
        },
        ['pants'] = {
            Component = 4,
            Label = 'Hose',
            name = 'pants',
            icon = 'images/clothingTypes/pants.png'
        },
        ['shirt'] = {
            Component = 11,
            Label = 'Torso',
            name = 'shirt',
            icon = 'images/clothingTypes/torso.png'
        },
        ['shoes'] = {
            Component = 6,
            Label = 'Schuhe',
            name = 'shoes',
            icon = 'images/clothingTypes/shoes.png'
        },
        ['hat'] = {
            Component = 0,
            Label = 'Hut',
            name = 'hat',
            icon = 'images/clothingTypes/hat.png'
        },
        ['glasses'] = {
            Component = 1,
            Label = 'Brille',
            name = 'glasses',
            icon = 'images/clothingTypes/glasses.png'
        },
        ['earrings'] = {
            Component = 2,
            Label = 'Ohrringe',
            name = 'earrings',
            icon = 'images/clothingTypes/earrings.png'
        },
        ['chain'] = {
            Component = 7,
            Label = 'Kette',
            name = 'chain',
            icon = 'images/clothingTypes/chains.png'
        }
    }
}

StringToHash = function(name)
    for hash, weaponName in pairs(Config.HashToString) do
        if weaponName == name then
            return hash
        end
    end
end
