--RIFLE--
AddTextEntry("WEAPON_AR15", "AR-15")
AddTextEntry("WEAPON_DE", "Desert Eagle")
AddTextEntry("WEAPON_M4", "M4")
AddTextEntry("WEAPON_M70", "M70")
AddTextEntry("WEAPON_MK14", "MK14")
AddTextEntry("WEAPON_REMINGTON", "Remington 870")
AddTextEntry("WEAPON_SCARH", "SCAR-H")
AddTextEntry("WEAPON_UZI", "UZI")
AddTextEntry("WEAPON_MP9", "MP9")
AddTextEntry("WEAPON_HK416", "HK-416")
AddTextEntry("WEAPON_MP5", "MP5")
AddTextEntry("WEAPON_AKS74", "AKS74-U")
AddTextEntry("WEAPON_GLOCK18C", "Glock18c")

--MELEE--
AddTextEntry("WEAPON_SHIV", "Shiv")
AddTextEntry("WEAPON_SLEDGEHAMMER", "Sledge Hammer")
AddTextEntry("WEAPON_COLBATON", "Teleskop")
AddTextEntry("WEAPON_BAYONETKNIFE", "Bayonet")
AddTextEntry("WEAPON_KATANA", "Katana")
AddTextEntry("WEAPON_KHAMMER", "Axe Of Kratos")
AddTextEntry("WEAPON_BBAT", "Crazy Bat")
AddTextEntry("WEAPON_BBBAT", "Vernichter")
AddTextEntry("WEAPON_CANDYAXE", "Candy Axe Picaxe")
AddTextEntry("WEAPON_LIGHT", "Lightsaber")
AddTextEntry("weapon_DHAMMER", "Deadric Hammer")
AddTextEntry("WEAPON_DSWORD", "Deadric Sword")
AddTextEntry("WEAPON_DAXE", "Deadric Axe")
AddTextEntry("WEAPON_DDAGGER", "Crazy Dagger")
AddTextEntry("WEAPON_GOOFY", "Goofy Hammer")
AddTextEntry("WEAPON_HHAMMER", "Crazy Hammer")
AddTextEntry("WEAPON_KKNIFE", "Knife")
AddTextEntry("WEAPON_MIST", "Mist Splitter")
AddTextEntry("WEAPON_RAINBOWSMASH", "Rainbow Smash Picaxe")
AddTextEntry("WEAPON_WLIGHT", "White Lightsaber")
AddTextEntry("WEAPON_SWORD", "Yone Sword")
AddTextEntry("WEAPON_DIA", "Mini Diamond Pickaxe")